camunda.bpm:
  admin-user:
    id: k
    password: k
    firstName: Kermit
  filter:
    create: All tasks

cj.software.camunda.monitoring:
   cron-settings: 10 * * * * ?
   download-url: http://www.nasa.gov