camunda.bpm:
  admin-user:
    id: kermit
    password: kermit
    firstName: Kermit
  filter:
    create: All tasks

to-be-checked:
  entries:
    acceptance:
      databaseConnection: jdbc:postgresql:acceptance
      user: acceptance
      password: acceptance
      selectStatement: select count(*) from alert
      limit: 3
      resource-url: https://www.berlin-recycling-volleys.de/index.php/de/
    experiments-trigger:
      databaseConnection: jdbc:postgresql:experiments
      user: experiments
      password: experiments
      selectStatement: select count(*) from cjtrigger where state = 'failed'
      limit: 0
      resource-url: https://www.chiefs.com
input:
  name: raja
  age: 12
  somedata:
    abcd: 1 
    bcbd: 2
    cdbd: 3