camunda.bpm:
  admin-user:
    id: kermit
    password: kermit
    firstName: Kermit
  filter:
    create: All tasks

cj.software.experiments.camunda.10-mail:
  addtl-url: http://localhost:8080/
    
#spring.datasource:
#  url: jdbc:postgresql://localhost:5432/optimize
#  driverClassName: org.postgresql.Driver
#  username: optimize
#  password: optimize
