camunda.bpm:
  admin-user:
    id: kermit
    password: kermit
    firstName: Kermit
  filter:
    create: All tasks

cj.software.experiments.camunda.10:
  addtl-url: https://www.nasa.gov
    
#spring.datasource:
#  url: jdbc:postgresql://localhost:5432/optimize
#  driverClassName: org.postgresql.Driver
#  username: optimize
#  password: optimize
