camunda.bpm:
  admin-user:
    id: kermit
    password: kermit
    firstName: Kermit
  filter:
    create: All tasks

spring.mail:
  host: smtp.aol.com
  port: 587
  username: cjacobme@aol.com
  properties.mail.smtp.auth: true
  properties.mail.smtp.starttls.enable: true
    
#spring.datasource:
#  url: jdbc:postgresql://localhost:5432/optimize
#  driverClassName: org.postgresql.Driver
#  username: optimize
#  password: optimize
