camunda.bpm:
  admin-user:
    id: kermit
    password: kermit
    firstName: Kermit
  filter:
    create: All tasks
  database:
    schema-update: false
    type: postgres
  authorization:
    enabled: true
    
spring.datasource:
  url: jdbc:postgresql://localhost:5432/messaging
  driverClassName: org.postgresql.Driver
  username: messaging
  password: messaging
